### ISSUE TITLE
[Feature request] Add extra flags for running Flye

### ISSUE THREAD

**Issue by pdobbler** [gbouras13/hybracter#101]
Hi @gbouras13, thank you for hybracter!

**Is your feature request related to a problem? Please describe.**

I'm running 5 bacterial genomes through hybracter. These are high-depth sequencing done with nanopore. However, for 2 genomes, Flye fails with 'No disjointigs were found' error. It seems to be a problem when too much data is given to Flye. 

I used the  `--subsample_depth 100` flag from hybracter without success.

**Describe the solution you'd like**
Would it be too disruptive to add an option to add further options to run Flye? Something like:  `--extra-params-flye "--meta"` 

For these cases, it was [suggested](https://github.com/mikolmogorov/Flye/issues/128)  use `--meta` or subsampling during the disjointigs step 

In this case, running Flye with `--meta` worked for my 2 genomes that were failing before. 

Would a solution around this be possible?

**Comment by gbouras13** [comment]
Hi @pdobbler 

Very reasonable and easy request - luckily, I am planning on releasing a new version today implementing Medaka v2 and `--bacteria` after Ryan Wick's blogpost https://rrwick.github.io/2024/10/17/medaka-v2.html. So should be available soon.

George

**Comment by gbouras13** [comment]
implemented in v0.10.0 - let me know if that works for you @pdobbler

**Comment by pdobbler** [comment]
That's great! Thank you @gbouras13, I'll give it a go now!
