### ISSUE TITLE
Medaka error in hybracter v0.11.0 on specific computer

### ISSUE THREAD

**Issue by llk578496** [gbouras13/hybracter#111]
Hi @gbouras13 ,

We're encountering a computer-specific issue with `hybracter v0.11.0`. The following command runs successfully on other machines but fails during the medaka step on one particular computer:

`hybracter long-single -l 02_fastq/BA00000057.fastq.gz -s BA00000057 -c 5200000 -o 03_assembly/03.1_hybracter/BA00000057 -t 64 --subsample_depth 120 --min_depth 100 --medakaModel r1041_e82_400bps_bacterial_methylation --medaka_override`

However, we encountered the following errors during the medaka step:

```
Traceback (most recent call last):
  File "/home/user/miniforge3/envs/hybracter-v0.11.0/lib/python3.12/site-packages/hybracter/workflow/conda/21bdcd97287bbafaddd2c6e70c575533_/lib/python3.11/site-packages/medaka/medaka.py", line 35, in __call__
    model_fp = medaka.models.resolve_model(val)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/hybracter-v0.11.0/lib/python3.12/site-packages/hybracter/workflow/conda/21bdcd97287bbafaddd2c6e70c575533_/lib/python3.11/site-packages/medaka/models.py", line 104, in resolve_model
    raise DownloadError(
medaka.models.DownloadError: The model file for r1041_e82_400bps_bacterial_methylation is not already installed and could not be downloaded. Check you are connected to the internet and try again.
```
The full medaka log is attached as [BA00000057.log](https://github.com/user-attachments/files/18057587/BA00000057.log) and the [hybracter.log](https://github.com/user-attachments/files/18057585/hybracter.log) is also attached.

We also tried running the same command on other computers, and it completed successfully without any errors. Could this issue be related to this specific computer?

Thank you very much for your assistance!

Best regards,
Eddie

**Comment by gbouras13** [comment]
Hi @llk578496 .

Not a `lrge` issue thankfully :) Thanks for your bug reports, they are really useful.

This might be a trivial/dumb question, but is the computer causing the error connected to the internet? The error seems to be caused by failure to download the medaka model. 

Also, perhaps try `hybracter install -m` ? This will install the medaka models separately. 

If the error persists, can you give me some more details regarding the computer's specs?

George

**Comment by llk578496** [comment]
Hi @gbouras13 

I'm happy to try out `hybracter` and provide useful bug reports.

The computer is connected to the internet. However, when I attempted to run `hybracter install -m`, I encountered the following error:

```
Traceback (most recent call last):
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 35, in __call__
    model_fp = medaka.models.resolve_model(val)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/models.py", line 104, in resolve_model
    raise DownloadError(
medaka.models.DownloadError: The model file for r103_fast_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/bin/medaka", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 836, in main
    args.func(args)
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 366, in download_models
    fp = ResolveModel('--model', 'model')(None, ns, [model], 'model')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 38, in __call__
    raise RuntimeError(msg.format(self.dest, str(e)))
RuntimeError: Error validating model from '--model' argument: The model file for r103_fast_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.
[Mon Dec  9 16:01:40 2024]
Error in rule download_medaka_models:
    jobid: 2
    output: /home/user/miniforge3/envs/hybracter-v0.11.0/lib/python3.12/site-packages/hybracter/workflow/../databases/medaka.flag
    conda-env: /home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_
    shell:
        
        medaka tools download_models
        touch /home/user/miniforge3/envs/hybracter-v0.11.0/lib/python3.12/site-packages/hybracter/workflow/../databases/medaka.flag
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-12-09T160122.889208.snakemake.log
WorkflowError:
At least one job did not complete successfully.
[2024:12:09 16:01:40] ERROR: Snakemake failed
```
[2024-12-09T160122.889208.snakemake.log](https://github.com/user-attachments/files/18058254/2024-12-09T160122.889208.snakemake.log)

I've also attached the computer specifications. [spec.txt](https://github.com/user-attachments/files/18058308/spec.txt)

Thank you very much!

Best regards,
Eddie

**Comment by gbouras13** [comment]
Hi @llk578496 ,

This looks like an error beyond my knowledge - I will make an issue in the Medaka repository.

**Comment by llk578496** [comment]
Hi @gbouras13 

Thank you very much!

Best regards,
Eddie

**Comment by gbouras13** [comment]
An alternative @llk578496  for you on this computer is to use the container build - I recently made and updated a `v0.11.0` version today.

George

**Comment by llk578496** [comment]
Hi @gbouras13 ,

We discovered that the issue was due to our network connectivity, as we were unable to download the `r1041_e82_400bps_bacterial_methylation` model from the [Medaka GitHub repository](https://github.com/nanoporetech/medaka/raw/refs/heads/master/medaka/data/r1041_e82_400bps_bacterial_methylation_model_pt.tar.gz?download=).

We manually downloaded the model from another computer and placed it in `~/miniforge3/.../site-packages/medaka/data`. The pipeline is running smoothly now, so I will close this issue.

Thank you very much for your help!

Best regards,
Eddie
