### ISSUE TITLE
BWA index bug + missing folder for ALE sam outputs

### ISSUE THREAD

**Issue by simone-pignotti** [gbouras13/hybracter#13]
Hi, I have encountered a couple of issues while running hybracter: first, the `bwa_index` rule failed and I can't find the reason (I have activated the same environment and ran the command again, and that works).

```
Error in rule bwa_index:
    jobid: 122
    input: out/processing/complete/medaka_rd_2/S5/consensus.fasta
    output: out/processing/complete/medaka_rd_2/S5/consensus.fasta.bwt
    conda-env: .snakemake_conda/6be766c09fe1748a60e50f848434e177_
    shell:

        bwa index out/processing/complete/medaka_rd_2/S5/consensus.fasta

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bwa_index since they might be corrupted:
out/processing/complete/medaka_rd_2/S5/consensus.fasta.bwt
```

The only hint I could find in the stderr log is:
```
[bwa_index] Update BWT... [bwt_bwtupdate_core] inconsistent bwt_size Abort!
```

The following rule failed too:
```
Error in rule assess_medaka_rd_2:
    jobid: 128
    input: out/processing/qc/fastp/S5.fastq.gz, out/processing/complete/medaka_rd_2/S5/consensus.fasta, out/processing/ale_scores_complete/S5/medaka_rd_1.score
    output: out/processing/ale_scores_complete/S5/medaka_rd_2.score, out/processing/ale_out_files/S5/medaka_rd_2.ale, out/processing/ale_sams/S5medaka_rd_2.sam
    log: out/stderr/ale/S5_medaka_rd_2.log (check log file(s) for error details)
    conda-env: .snakemake_conda/b18b79b596f03436150e20b347f0105c_
    shell:

        bwa index out/processing/complete/medaka_rd_2/S5/consensus.fasta
        bwa mem -t 16 -a out/processing/complete/medaka_rd_2/S5/consensus.fasta out/processing/qc/fastp/S5_1.fastq.gz > out/processing/ale_sams/S5medaka_rd_2.sam 2> out/stderr/ale/S5_medaka_rd_2.log
        ALE out/processing/ale_sams/S5medaka_rd_2.sam out/processing/complete/medaka_rd_2/S5/consensus.fasta out/processing/ale_out_files/S5/medaka_rd_2.ale 2> out/stderr/ale/S5_medaka_rd_2.log
        grep "# ALE_score: " out/processing/ale_out_files/S5/medaka_rd_2.ale | sed 's/# ALE_score: //' > out/processing/ale_scores_complete/S5/medaka_rd_2.score
        rm out/stderr/ale/S5_medaka_rd_2.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile out/stderr/ale/S5_medaka_rd_2.log not found.
```

My best guess is that the bwa index is erroneously constructed twice, both in `bwa_index` and in `assess_medaka_rd_2` (which has `consensus.fasta` as input, not `consensus.fasta.bwt`), so the `assess_medaka_rd_2` rule was executed in parallel to `bwa_index`, which caused an inconsistency in the `consensus.fasta.bwt` file.

Also, `out/processing/ale_sams` didn't exist.

Two other minor things:
1. missing `_` separator in `out/processing/ale_sams/S5medaka_rd_2.sam`
2. `assess_medaka_rd_2` only uses `_1.fastq.gz`, is this a design choice?

Thanks in advance!

**Comment by gbouras13** [comment]
Hi @simone-pignotti ,

Thank you so much for this and your PR #14 .

I would assuming your diagnosis of the issue is correct. I've run CI and local tests and it seems to work fine. Also thanks for the bugfixes with separators and the polypolish version in that PR.

Regarding the question about `assess_medaka_rd_21 only uses 1_1.fastq.gz`, is this a design choice?

Yes for all of the assess rules, I only decided to use R1 reads. I figured it would speed up running ALE (which is run 3 or 4 times) without really losing any accuracy in the ALE. ALE is just an estimate anyway.

George
