### ISSUE TITLE
[BUG] Add required channels to install instructions/documentation

### ISSUE THREAD

**Issue by ammaraziz** [gbouras13/hybracter#40]
**Describe the bug**
The install instructions are missing channels, specifically bioconda and conda-forge.

**To Reproduce**

The instructions are:

```
mamba create -n hybracterENV hybracter
```

Unless the user has added bioconda channel as a default the above will fail to find `hybracter`. 

There are also some distributions of mamba (eg micromamba) which do not have any default channels. This causes a heap of issues when installing bioconda tools which require 'external' tools from conda-forge.

I recommend adding both channels explicitly to the instructions.

```
mamba create -n hybracterENV -c bioconda -c conda-forge hybracter
```

A bit verbose but better safe than sorry.

**Comment by gbouras13** [comment]
Hi @ammaraziz ,

Agree with all of this, thanks for pointing this out. I'll update the documentation shortly.

**Comment by gbouras13** [comment]
Hi @ammaraziz ,

I've added this to the docs for v0.5.0. Thanks again for picking this up.

George
