### ISSUE TITLE
[Feature request] Download all medaka models with test-long (and test-hybrid)?

### ISSUE THREAD

**Issue by lxsteiner** [gbouras13/hybracter#48]
In order to use hybracter on an offline node, building the environments and downloading needed packages is suggested with running `test-long` (and/or `test-hybrid`) - this should/could also download all medaka models, instead of only the one used for the test dataset. Otherwise a hint is needed to manually copy the missing model into the environment `medaka/data` model folder.

**Comment by gbouras13** [comment]
Better to be in the hybracter install command I think but agreed it would be a good feature, I will implement it in the next update thanks @lxsteiner.

George
