### ISSUE TITLE
[BUG] Medaka failure on MacOS 

### ISSUE THREAD

**Issue by andreagp96** [gbouras13/hybracter#56]
**Describe the bug**
There is a problem with medaka when executing hybracter test-hybrid after installing hybracter with mamba on MacOS Intel Core i5 (python version 3.12.2)

**To Reproduce**
Steps to reproduce the behaviour, including the
1. Command executed:
mamba create -n hybracterENV -c conda-forge -c bioconda -c defaults hybracter
conda activate hybracterENV
hybracter install
hybracter test-hybrid

2. Error message:
Creating conda environment ../envs/medaka.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /usr/local/Caskroom/miniforge/base/envs/hybracterENV/lib/python3.12/site-packages/hybracter/workflow/envs/medaka.yaml:
Command:
mamba env create --quiet --file "/usr/local/Caskroom/miniforge/base/envs/hybracterENV/lib/python3.12/site-packages/hybracter/workflow/conda/f44c0ad0dfbeed7f0e74bbd780b5c7e7_.yaml" --prefix "/usr/local/Caskroom/miniforge/base/envs/hybracterENV/lib/python3.12/site-packages/hybracter/workflow/conda/f44c0ad0dfbeed7f0e74bbd780b5c7e7_"
Output:
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following package could not be installed
└─ medaka 1.8.0  is not installable because it requires
   ├─ libcurl >=7.88.1,<8.0a0  with the potential options
   │  ├─ libcurl 7.88.1 would require
   │  │  └─ openssl >=3.0.8,<4.0a0 , which can be installed;
   │  ├─ libcurl 7.88.1 would require
   │  │  └─ openssl >=3.1.0,<4.0a0 , which can be installed;
   │  └─ libcurl 7.88.1 conflicts with any installable versions previously reported;
   └─ openssl >=1.1.1t,<1.1.2a , which conflicts with any installable versions previously reported.

[2024:02:20 12:53:57] ERROR: Snakemake failed

**Desktop (please complete the following information):**
 - OS: macOS Ventura v13.6.4
 - Browser: Firefox v122.0.1 (64-bit)

**Additional context**
I could solve the issue by deleting the specific version of medaka (1.8.0) in the f44c0ad0dfbeed7f0e74bbd780b5c7e7_.yaml file and then I executed the following sentence: 
mamba env create --quiet --file "/usr/local/Caskroom/miniforge/base/envs/hybracterENV/lib/python3.12/site-packages/hybracter/workflow/conda/f44c0ad0dfbeed7f0e74bbd780b5c7e7_.yaml" --prefix "/usr/local/Caskroom/miniforge/base/envs/hybracterENV/lib/python3.12/site-packages/hybracter/workflow/conda/f44c0ad0dfbeed7f0e74bbd780b5c7e7_"
After this, I ran again the hybracter test-hybrid command and it worked! Finally, I checked the recently installed medaka version and it was 1.11.3. 
So, I post this issue in case there is a better solution or somebody encounters the same problem.

Thanks!

**Comment by gbouras13** [comment]
This is awesome thanks @andreagp96 ,

Medaka is very painful to install (especially on Macs!) - luckily we can stop using it for the newest Nanopore data (I am shortly going to make this a default in hybracter) - see https://rrwick.github.io/2023/12/18/ont-only-accuracy-update.html

George

**Comment by andreagp96** [comment]
Great!! 

Thanks a lot,

Andrea
