### ISSUE TITLE
[Feature request] Addding the option to write the database to a specific directory

### ISSUE THREAD

**Issue by npbhavya** [gbouras13/hybracter#60]
I am running the command, 
`hybracter install -o temp -d hybracterDB`

> Running into the  error 
> 2024-03-13 10:17:42.184 | INFO     | plassembler:download:1123 - Checking database installation at hybracterDB
> 2024-03-13 10:17:42.184 | ERROR    | plassembler.utils.db:check_db_installation:43 - Directory hybracterDB already exists and force was not specified. Please specify -f or --force to overwrite hybracterDB

But -f option is only within plassembler, so adding -f to the above hybracter command is not being translated. So just adding -f option to the plassembler download rule would fix this. 

I am not sure why the directory "hybracterDB" already exists since its the first time I am defining that directory

**Comment by gbouras13** [comment]
This should be an easy fix @npbhavya thanks for raising it.

I think the cause is a Snakemake reason - it will make the output files/directories at the start of a rule so you always need `-f`.

George
