### ISSUE TITLE
[BUG] No plasmid in final output

### ISSUE THREAD

**Issue by CorentinEscobar** [gbouras13/hybracter#74]
Hi,

I have a problem with the assembly since yesterday. I assemble bacterial genomes which contain plasmids with Hybracter and since yesterday, I haven't any plasmids in the final output. It worked very well last week because I assembled this same genome with hybracter and I had the plasmid in final output.
Do you know why it does that ? And do you know how to fix it ?
Thanks

Corentin

**Comment by CorentinEscobar** [comment]
Hi George,

Looking in the intermediate log files I noticed that the problem came from Plassembler, and more precisely from SPADES when unicycler is running. SPADES goes into error (OS return -11) and the plasmids are therefore not present in the output file. So in the final output of hybracter doesn't find the plasmids.
According to the issues on the SPADES github, this could be due to lack of memory. By reducing the number of threads I no longer have this problem. However, it takes a little longer ;)

You may have another way to resolve this problem while keeping a high number of threads for all steps except unicycler ?

Thank you !

Corentin

**Comment by gbouras13** [comment]
Hi @CorentinEscobar ,

Glad to hear it worked in the end - the best way is to modify this line 

https://github.com/gbouras13/hybracter/blob/0acfb01454545116bac91e53db2b162d537f07f6/hybracter/workflow/rules/assembly/plassembler.smk#L30

to e.g. (for 1 thread)

```
threads: 1
```

George

**Comment by CorentinEscobar** [comment]
Ok perfect ! Thank you @gbouras13 
Corentin
