### ISSUE TITLE
New parameter pointing to the raw data

### ISSUE THREAD

**Issue by oschwengers** [gbouras13/hybracter#76]
Hi George,
thanks so much for this wonderful tool - I got awesome results so far!

I just thought about an additional `--data` parameter that would accept the path to a data directory where all the raw incoming reads are stored. By this, users don't have to put these often very long paths into the `csv` file which might be error prone and a bit inconvenient. So if there is a path provided via `--data`, the `csv` file will only contain the file names.

How about that? Thanks!

**Comment by vdejager** [comment]
Hi george,

is the --datadir option in 0.8.0 now mandatory? Whenever I use full paths in my sample.csv, hybracter complains that it cannot find the files. If I copy the files in my directory from where I run hybracter, it runs as expected. Note: I have to use the docker container on our HPC.

does the datadir option take multiple arguments? (to accomodate reads in different directories, e.g. nanopore in one, illumina in the other)

**Comment by gbouras13** [comment]
Hi @vdejager ,

Do you mind sharing an error log? It was certainly not my intention for it to be mandatory. It could be container specific too, not sure. 

It does not take multiple arguments, but that is a great idea to be honest - assuming this is a bug I have to fix, I'll think about implementing that.

George

**Comment by gbouras13** [comment]
@vdejager, your request is implemented in v0.9.0. `--datadir "longdir,shortdir"` where the directories are separated by a comma should work

George
