### ISSUE TITLE
[BUG] hybracter install problem

### ISSUE THREAD

**Issue by gaworj** [gbouras13/hybracter#80]
Hi George,

Thank you for such great tool!

I get stuck on hybracter install command:

hybracter install -m -o temp -d /media/jang/SSD2/databases/hybracter_db

hybracter version 0.7.3

 _           _                    _            
| |__  _   _| |__  _ __ __ _  ___| |_ ___ _ __ 
| '_ \| | | | '_ \| '__/ _` |/ __| __/ _ \ '__|
| | | | |_| | |_) | | | (_| | (__| ||  __/ |   
|_| |_|\__, |_.__/|_|  \__,_|\___|\__\___|_|   
       |___/

[2024:06:06 21:29:03] Config file temp/config.yaml already exists. Using existing config file.
[2024:06:06 21:29:03] Updating config file with new values
[2024:06:06 21:29:03] Writing config file to temp/config.yaml
[2024:06:06 21:29:03] ------------------
[2024:06:06 21:29:03] | Runtime config |
[2024:06:06 21:29:03] ------------------

args:
  databases: /media/jang/SSD2/databases/hybracter_db
  log: temp/hybracter.log
  medaka: true
  output: temp
qc:
  compression: 5
  hostRemoveFlagstat: -f 4 -F 3584
  minimapIndex: -I 8G
  minimapModel: map-ont
resources:
  big:
    cpu: 16
    mem: 32000
    time: '23:59:00'
  med:
    cpu: 8
    mem: 16000
    time: 08:00:00
  sml:
    cpu: 1
    mem: 4000
    time: 00:00:05

[2024:06:06 21:29:03] ---------------------
[2024:06:06 21:29:03] | Snakemake command |
[2024:06:06 21:29:03] ---------------------

snakemake -s /home/jang/miniconda3/envs/hybracter/lib/python3.12/site-packages/hybracter/workflow/install.smk --configfile temp/config.yaml --jobs 1 --use-conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs --conda-frontend mamba
Config file /home/jang/miniconda3/envs/hybracter/lib/python3.12/site-packages/hybracter/workflow/../config/config.yaml is extended by additional config specified via the command line.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Creating conda environment /home/jang/miniconda3/envs/hybracter/lib/python3.12/site-packages/hybracter/workflow/envs/plassembler.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/jang/miniconda3/envs/hybracter/lib/python3.12/site-packages/hybracter/workflow/envs/plassembler.yaml:
Command:
mamba env create --quiet --no-default-packages --file "/media/jang/SSD2/genome_analysis/test_hybracter/.snakemake/conda/15bfb960cecdaf8262a624235f71c2d6_.yaml" --prefix "/media/jang/SSD2/genome_analysis/test_hybracter/.snakemake/conda/15bfb960cecdaf8262a624235f71c2d6_"
Output:
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
done
ERROR conda.core.link:_execute(952): An error occurred while installing package 'conda-forge::perl-5.32.1-7_hd590300_perl5'.
Rolling back transaction: ...working... done

[Errno 22] Invalid argument: '/media/jang/SSD2/genome_analysis/test_hybracter/.snakemake/conda/15bfb960cecdaf8262a624235f71c2d6_/man/man3/App::Cpan.3'
()

[2024:06:06 21:31:01] ERROR: Snakemake failed

When I tried to run all of the tests using commands:
hybracter test-hybrid 
hybracter test-long 
everything worked fine.

Any hints?

Bests,
Jan

**Comment by gbouras13** [comment]
Hi @gaworj ,

This is a weird error - it looks like perl in the plassembler environment couldn't solve. Never seen it before and doesn't make too much sense as the environment installation must have worked if the tests did.

Do you have access to singularity/docker? I'd recommend the container installation (in the README) as you don't need to install a database.

George

**Comment by gaworj** [comment]
Hi George,

I was working on Ubuntu 16.04 with Conda 4.14.0.  When switched to another workstation witn Ubuntu 20.04 and newest mamba everything worked fine.
OK, I will try to install it on the first system using docker.

Bests,
Jan
