### ISSUE TITLE
[Feature request] Add --min_depth in the QC step

### ISSUE THREAD

**Issue by llk578496** [gbouras13/hybracter#89]
**Is your feature request related to a problem? Please describe.**

Hi @gbouras13,

I would like to inquire if it's possible to add an option `--min_depth` in the QC step for the raw reads.

Thank you very much.

Best regards,
Eddie

**Comment by gbouras13** [comment]
Hi @llk578496 

i’m a bit confused at this request - what use case do you foresee for this?

george

**Comment by llk578496** [comment]
Hi @gbouras13,

To elaborate further, I would like to propose adding an option `--min_depth` in the QC step for the raw reads. This option could be used to set a minimum depth threshold, for example, 100. If the depth falls below this threshold, the QC for raw reads would fail, and the assembly process would be stopped.

This additional check could help identify and prevent issues early on in the pipeline, potentially saving time and computational resources.

Thank you for considering this suggestion.

Best regards,
Eddie

**Comment by gbouras13** [comment]
Sound reasonable. Might be sneaky hard to implement in snakemake though without disrupting the rest of the pipeline too much. I'm going to put in an improvement soon with archaea, so when I do that I'll give this a crack.

George

**Comment by llk578496** [comment]
Thank you very much!

Best regards,
Eddie

**Comment by llk578496** [comment]
Hi @gbouras13 ,

I need to reopen this issue as I've encountered difficulties with the latest version v0.9.0 of Hybracter.

I attempted to run the following command:
`hybracter long-single -l 02_fastq/ont/23M7739639.fastq.gz -s 23M7739639 -c 2900000 -o 04_bactopia/04.2_done/ont/tree/assembly/hybracter/23M7739639 -t 18 --min_depth 100 --no_medaka`

However, it resulted in these errors:

> #####I skipped the unrelated logs#####
> The total number of bases of long-read sequencing is 289837809, which is lower than the required minimum value 290000000 based on the chromosome size multiplied by the --min_depth parameter.
>  Please check --min_depth and/or get more long-read sequencing data! Hybracter will stop here.
> RuleException:
> CalledProcessError in file /home/ha/miniconda3/envs/hybracter-v0.9.0/lib/python3.12/site-packages/hybracter/workflow/rules/processing/coverage.smk, line 88:
> Command 'source /home/ha/miniconda3/bin/activate '/home/ha/miniconda3/envs/hybracter-v0.9.0/lib/python3.12/site-packages/hybracter/workflow/conda/05aa8ab6eea08c92aaf8ace833e5815c_'; set -euo pipefail;  python /media/ha/38f8aab2-d252-435d-8e6f-9dae34c11324/BAC/WGS/.snakemake/scripts/tmp1_jgtyi9.lr_coverage.py' returned non-zero exit status 1.
> [Thu Sep 19 15:09:58 2024]
> Error in rule estimate_lr_coverage:
>     jobid: 8
>     input: 04_bactopia/04.2_done/ont/tree/assembly/hybracter/23M7739639/processing/qc/seqkit/23M7739639_long.txt, 04_bactopia/04.2_done/ont/tree/assembly/hybracter/23M7739639/processing/kmc/23M7739639/23M7739639_kmcLOG.txt
>     output: 04_bactopia/04.2_done/ont/tree/assembly/hybracter/23M7739639/processing/qc/coverage/23M7739639_lr.txt
>     conda-env: /home/ha/miniconda3/envs/hybracter-v0.9.0/lib/python3.12/site-packages/hybracter/workflow/conda/05aa8ab6eea08c92aaf8ace833e5815c_
> 
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: .snakemake/log/2024-09-19T150622.654666.snakemake.log
> WorkflowError:
> At least one job did not complete successfully.
> [2024:09:19 15:09:58] ERROR: Snakemake failed

I've verified that the FASTQ file size exceeds 290,000,000 bases, and I've encountered the same issue with additional samples. Could this be related to the --subsample_depth parameter [default:100]?

Best regards,
Eddie

**Comment by gbouras13** [comment]
Hi @llk578496 ,

Are you sure that the quality controlled long-read file is over 290M bases? `--subsample_depth` was written to work on that (as it is what ultimately is fed into the assembler), not the raw input data. So it might be the raw data has more, but the QC'd data has less.

George

**Comment by gbouras13** [comment]
Thanks @llk578496 I'll look into it - in that case, you are probably right that it is getting the subsample depth not the min qc depth

George

**Comment by gbouras13** [comment]
Actually, I think it is working as expected - try a slightly higher value for subsample_depth e.g. `--subsample_depth 120` or something.   Or alternatively, `--min_depth 90`.

`--min_depth` works on the post QCd reads, so it is quite likely that subsampling to approximately 100x will make the total read length lower than 100x, after trimming is done with filling. I was anticipating a use case lower than min depth 100x I guess (maybe 20x or 30x!)

George

**Comment by llk578496** [comment]
I just ran with `--subsample_depth 120` and `--min_depth 100` successfully. 

Thank you very much!

Best regards,
Eddie
