### ISSUE TITLE
Wrong variable name

### ISSUE THREAD

**Issue by simone-pignotti** [gbouras13/hybracter#9]
Hello! Thanks for developing hybracter (and the different tools it depends on), seems very promising!

I encountered a little bug while testing it, I believe the variable `dictReads` here should be `sampleDict` instead:

https://github.com/gbouras13/hybracter/blob/b9da0d2f7febf7494b01106aa518536894536859/hybracter/workflow/rules/preflight/samples.smk#L121

Cheers

**Comment by gbouras13** [comment]
Hi @simone-pignotti ,

This is indeed a bug. Thanks for picking it up and trying hybracter, let me know if you have any other feedback (once it works!)

If you fix that it should work. I am patching a fix and will release it as v0.1.1 today.

George

**Comment by gbouras13** [comment]
This is done now @simone-pignotti , give it a go with e.g. `pip install hybracter==0.1.1` and it should work a treat now.

**Comment by simone-pignotti** [comment]
Thanks for the quick fix @gbouras13!
